### ISSUE TITLE
Can not have more than one LogConfig

### ISSUE THREAD

**Issue by andre-paraense** [fredg02/se.bitcraze.crazyflie.lib#1]
In the LoggingExample, if you try to have more than one LogConfig at the same time, one of them will not work, and the reason is not clear for the developer, who only get an error 17.

I have tried the same slightly modifying the "basicLong.py" in the python library and it works just fine.

**Comment by fredg02** [comment]
This issue has been fixed. Also the error reporting in the example is better now and should tell the developer what the problem is.
